environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      configuration: Debug
      platform: x86
      generator: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      configuration: Debug
      platform: x64
      generator: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      configuration: Release
      platform: x86
      generator: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      configuration: Release
      platform: x64
      generator: "Visual Studio 14 2015"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Debug
      platform: x86
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Debug
      platform: x64
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Release
      platform: x86
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      configuration: Release
      platform: x64
      generator: "Visual Studio 15 2017"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Debug
      platform: x86
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Debug
      platform: x64
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release
      platform: x86
      generator: "Visual Studio 16 2019"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      configuration: Release
      platform: x64
      generator: "Visual Studio 16 2019"

init:
  # Variables
  - if "%platform%"=="x86" (set generator_platform=Win32) else (set generator_platform=x64)
  # Info
  - cmake --version
  - msbuild /version

install:
  - git submodule update --init --recursive

  # SFML
  - git clone --recurse --depth 1 https://github.com/SFML/SFML "%TMP%/sfml_local"
  - pushd "%TMP%/sfml_local"
  - mkdir cmake-build
  - pushd cmake-build
  - mkdir "%TMP%/sfml_install"
  - cmake -G "%generator%" -A "%generator_platform%" -DCMAKE_CONFIGURATION_TYPES="%configuration%" -DCMAKE_BUILD_TYPE="%configuration%" -DCMAKE_INSTALL_PREFIX="%TMP%/sfml_install" ..
  - cmake --build . --config "%configuration%" --target install -- /M

  # Dear ImGui
  - git clone --recurse --depth 1 https://github.com/ocornut/imgui %TMP%/imgui_local

build_script:
  - pushd "%APPVEYOR_BUILD_FOLDER%"
  - mkdir cmake-build
  - pushd cmake-build
  - cmake -G "%generator%" -A "%generator_platform%" -DCMAKE_CONFIGURATION_TYPES="%configuration%" -DCMAKE_BUILD_TYPE="%configuration%" -DCMAKE_PREFIX_PATH="%TMP%/sfml_install" -DSFML_DIR="%TMP%/sfml_install" -DIMGUI_DIR="%TMP%/imgui_local" -DBUILD_SHARED_LIBS=ON ..
  - cmake --build . --config "%configuration%" -- /M
