name: clang-format

on:
  - push
  - pull_request

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: '.'
          extensions: 'h,cpp'
          clangFormatVersion: 13
          style: file
